version: "3.7"
services:
  datascience-demo:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - [cite_start]JUPYTER_TOKEN=root [cite: 1]
      - [cite_start]JULIA_VERSION=1.7.1 [cite: 1]
      - POWER_BI_ENDPOINT=https://api.powerbi.com/beta/your-long-key-here
    volumes:
      - ./notebooks:/home/jovyan/notebooks
    ports:
      - 8888:8888
    container_name: datascience
